manifests: update kubernetes manifests to include new options also fix typo i made on docs and in the principal cmd
Signed-off-by: Christopher Coco <ccoco@redhat.com>

diff --git a/install/helm-repo/argocd-agent-agent/templates/tests/test-configMap.yaml b/install/helm-repo/argocd-agent-agent/templates/tests/test-configMap.yaml
--- a/install/helm-repo/argocd-agent-agent/templates/tests/test-configMap.yaml
+++ b/install/helm-repo/argocd-agent-agent/templates/tests/test-configMap.yaml
@@ -75,6 +75,33 @@ spec:
           exit 1
         fi
         
+        # Test agent.log.level
+        if [ -f /etc/config/agent.log.resource-proxy-level ]; then
+          echo "✓ agent.log.resource-proxy-level exists"
+          cat /etc/config/agent.log.resource-proxy-levellevel
+        else
+          echo "✗ agent.log.resrouce-proxy-levellevel missing"
+          exit 1
+        fi
+        
+        # Test agent.log.level
+        if [ -f /etc/config/agent.log.redis-proxy-level ]; then
+          echo "✓ agent.log.redis-proxy-level exists"
+          cat /etc/config/agent.log.redis-proxy-level
+        else
+          echo "✗ agent.log.redis-proxy-level missing"
+          exit 1
+        fi
+        
+        # Test agent.log.level
+        if [ -f /etc/config/agent.log.grpc-level ]; then
+          echo "✓ agent.log.grpc-level exists"
+          cat /etc/config/agent.log.grpc-level
+        else
+          echo "✗ agent.log.grpc-level missing"
+          exit 1
+        fi
+        
         # Test agent.namespace
         if [ -f /etc/config/agent.namespace ]; then
           echo "✓ agent.namespace exists"
